# Generated by Django 5.1.1 on 2024-09-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_account_id',
            field=models.CharField(default='val', unique=True),
            preserve_default=False,
        ),
    ]
