# Generated by Django 5.1.1 on 2024-09-28 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('transactions', '0002_customtransactionsmodel_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtransactionsmodel',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customcustomermodel'),
        ),
    ]
