# Generated by Django 5.1.1 on 2024-10-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_customtransactionsmodel_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtransactionsmodel',
            name='transaction_id',
            field=models.CharField(default='null'),
        ),
    ]
