# Generated by Django 5.1.1 on 2024-10-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_customtransactionsmodel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtransactionsmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='customtransactionsmodel',
            name='transaction_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
