# Generated by Django 5.1.1 on 2024-10-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_customtransactionsmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtransactionsmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default='null', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customtransactionsmodel',
            name='transaction_id',
            field=models.CharField(max_length=255),
        ),
    ]
