# Generated by Django 5.1.1 on 2024-09-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custominvoicemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='custominvoicemodel',
            name='invoice_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
